name: flutter_scroll_gallery
author: Thong Ku <matong.mz@gmail.com>
homepage: https://github.com/dthongvl/flutter_scroll_gallery
description: A Flutter package that help you to create Image carousels with scroll thumbnail in bottom
version: 0.0.1

environment:
  sdk: '>=1.20.0 <2.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^0.12.0